# Generated by Django 4.2.4 on 2023-08-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='departamentoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='department.department'),
        ),
    ]
